[build]
  command = "npm run build"
  publish = "build"
  NODE_VERSION = "18"

[build.environment]
  NPM_FLAGS = "--prefer-offline --no-audit"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_TYPESCRIPT_COMPILE_ERROR = "ignore"
  NODE_VERSION = "18"
  GO_VERSION = "1.19"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
